### ISSUE TITLE
Unnecessary warning should be removed.

### ISSUE THREAD

**Issue by mafagafogigante** [seatgeek/fuzzywuzzy#100]
This is the first project I've ever seen to produce command line garble because an **optional** is not there.

You likely know I am talking about [this](https://github.com/seatgeek/fuzzywuzzy/blob/master/fuzzywuzzy/fuzz.py#L33).

#67 was closed after a mere package suggestion. @medecau made a very solid point: this pertains to the documentation, if it is optional, do not throw it at every terminal that will use the code.

I can throw in a PR removing that if you don't want to write it. It could maybe just be logged silently at a very high level.

**Comment by josegonzalez** [comment]
I'm :-1: on removing it. There are cases where a developer thinks they've installed the package but hasn't - because of differing python environments etc. - and thus I think it's important to raise this exception.

His statement is totally valid, but given that we don't give developers the option to choose *which* library they can use and attempt to use the fastest by default, I don't think it applies in this situation.

**Comment by mafagafogigante** [comment]
OK.
