### ISSUE TITLE
Out of Order Strings Issue

### ISSUE THREAD

**Issue by Jordan-Eckowitz** [seatgeek/fuzzywuzzy#120]
Firstly thank you for fuzzywuzzy - it's amazing!

I'm using 'token sort' and 'token set' as per the example @ [http://chairnerd.seatgeek.com/fuzzywuzzy-fuzzy-string-matching-in-python/](url) to compare “<HOME_TEAM> vs <AWAY_TEAM>” and another constructs strings as “<AWAY_TEAM> vs <HOME_TEAM>”.

I've found that by having the term 'vs' in both strings it's enough to get a 100% match even if the teams are completely different.

**Comment by bogdan-telenav** [comment]
@Marvo-Ging 
In my opinion this is not an issue because if you use _token_set("first string","second string ",partial=False) this will get you what you want but this method have by default partial=True.
So it will use partial_ratio method.
This will find the matching word (in your problem "vs") in both strings that will match and return 100.
For your problem you this method with partial=False
