### ISSUE TITLE
Difflib and python-Levenshtein give different ratios in some cases

### ISSUE THREAD

**Issue by theodickson** [seatgeek/fuzzywuzzy#128]
This is probably known and accepted, but since it's not mentioned in the docs I'll raise this anyway. In certain edge cases, difflib and python-Levenshtein give different ratios.
E.g.:
```
>>> from fuzzywuzzy import fuzz, StringMatcher
>>> import difflib

#As long as python-Levenshtein is available, that will be used for the following:
>>> fuzz.ratio("ababab", "aaaaab")
67

#Switch to difflib:
>>> fuzz.SequenceMatcher = difflib.SequenceMatcher
>>> fuzz.ratio("ababab", "aaaaab")
33
```

I don't know how python-Levenshtein works, but difflib first chooses the left-most longest block in the first sequence that matches any block in the second sequence. Then among the longest matches in the second sequence to this chosen block, it will choose the left-most.

What this means is that it is forced to choose the first "ab" in the first string, and then matches it to the only "ab" in the second, at the end. This means it cannot recurse either to the left or the right to look for more matching blocks, since this match is at the very beginning of the first string and at the very end of the second. So the ratio calculated is 33, since it has matched one third (4/12) of the total characters.

I'm assuming that in python-Levenshtein, it makes a decision about which matches to choose based not just on maximality and left-most-ness, but also on whether the pair of matches chosen allows subsequent recursion. This is because it scores 67, so must have matched eight of 12 characters, i.e. it must have matched "ab" and then two subsequent "a"s in each sequence, meaning it must have chosen the last "ab" in the first string. Either this or it can recurse to opposite sides in the two sequences but that surely isn't happening.

To show this, if we change the second sequence to "abaaaa", difflib will also score 67 (since it matches the first two characters of each sequence then recurses to the right). See as follows:

```
>>> fuzz.ratio("ababab", "abaaaa")
67

#And switching pack to python-Levenshtein, no change:
>>> fuzz.SequenceMatcher = fuzzywuzzy.StringMatcher.StringMatcher
>>> fuzz.ratio("ababab", "abaaaa")
67
```

**Comment by josegonzalez** [comment]
Yeah, I guess they are slightly different sometimes. For our use-case, python-Levenshtein works well, and it's what we suggest people use in production.

**Comment by nol13** [comment]
I'll add, having run into this trying to get all my test cases to match up, I thiink there are two separate things going on. python-Levenshtein calculates the ratio a bit differently that difflib using a different formula that uses Levenshtein distance (with replacement cost 2, if i understood the code right) instead of get_matching_blocks, and also the output of get_matching blocks can be different as well when it is used. (which can affect partial_ratio too independently)

Not sure where the difference comes from, prob something along the lines of what you said, but note that in this example the sum of the length of the blocks (# of matches) just happens to be equal, so if you did the ratio calculation difflib's way (2.0 * # of matches / combined length) you'd still get the same ratio both times, but you get a different score the python-Levenshtein way.

>>> from fuzzywuzzy import fuzz
>>> import difflib
>>> 
>>> s1 = "the cincinnati reds vs the new york mets"
>>> s2 = "new york mets vs atlanta braves"
>>> 
>>> fuzz.SequenceMatcher(None, s1, s2).get_matching_blocks()
[(6, 0, 1), (14, 8, 1), (16, 10, 1), (18, 12, 5), (27, 21, 1), (30, 24, 1), (33, 26, 1), (37, 29, 1), (39, 30, 1), (40, 31, 0)]
>>>
>>> fuzz.SequenceMatcher = difflib.SequenceMatcher
>>>
>>> fuzz.SequenceMatcher(None, s1, s2).get_matching_blocks()
[Match(a=27, b=0, size=13), Match(a=40, b=31, size=0)]

(*where "each triple is of the form (i, j, n), and means that a[i:i+n] == b[j:j+n].")

**Comment by siulkilulki** [comment]
The difference is because `difflib` uses the Ratcliff-Obershelp algorithm, not the Levenshtein distance. Probably the readme should be updated, because not always Levenshtein distance is used.
