### ISSUE TITLE
Why GLP License, why not Apache 2.0, BSD ot MIT

### ISSUE THREAD

**Issue by surendrasalke** [seatgeek/fuzzywuzzy#175]
Can't distribute

**Comment by josegonzalez** [comment]
Thats because we mistakenly vendored something that was GPL - `fuzzywuzzy/StringMatcher.py` - and no one has stepped up to rewrite it. Because GPL2 is viral, the whole thing became GPL2, so thats about it.

We cannot relicense it as long as we include that file. If this messes with your distribution, I apologize, but there isn't much we can do here.

**Comment by graingert** [comment]
@surendrasalke 

I've created fuzzywuzzymit, a fork without any GPL code in: https://pypi.python.org/pypi/fuzzywuzzymit

I've also made a PR to use this upstream package in fuzzywuzzy and apply the GPL code to it: https://github.com/seatgeek/fuzzywuzzy/pull/199

**Comment by josegonzalez** [comment]
The mentioned PR may not be wholly legal from a licensing perspective, so I would hesitate to use the fork before we get that sorted. Thanks.
