### ISSUE TITLE
Finding best matches in a list gives wrong results.

### ISSUE THREAD

**Issue by ardoi** [seatgeek/fuzzywuzzy#77]
The `process.extract` function doesn't seem to handle capitalised queries well with some scorers:

``` python
>>>fuzzywuzzy.fuzz.partial_ratio('Santa Ana','Santa Ana')
100
>>>fuzzywuzzy.process.extract('Santa Ana', ['Santa Ana', 'Manta'], scorer=fuzzywuzzy.fuzz.partial_ratio)
[('Manta', 80), ('Santa Ana', 77)]
```

This is because [here](https://github.com/seatgeek/fuzzywuzzy/blob/master/fuzzywuzzy/process.py#L84) the choice string is processed but the query string is not:

``` python
>>>fuzzywuzzy.process.extract('santa ana', ['Santa Ana', 'Manta'], scorer=fuzzywuzzy.fuzz.partial_ratio)
[('Santa Ana', 100), ('Manta', 80)]
```

With some other scorers (e.g., WRatio) things work fine because those processes both strings internally anyway.

A workaround I use right now is:

``` python
>>>fuzzywuzzy.process.extract('Santa Ana', ['Santa Ana', 'Manta'], scorer=fuzzywuzzy.fuzz.partial_ratio, processor=lambda x:x)
[('Santa Ana', 100), ('Manta', 80)]
```

**Comment by josegonzalez** [comment]
@acslater00 Thoughts?

**Comment by acslater00** [comment]
Yeah this definitely *looks* broken. 

Unfortunately I don't think it's safe to run `processor()` on the query because it isn't and hasn't been part of the spec. It makes sense when processing is just doing an encoding conversion and running `.lower()`, but it wouldn't make sense in a situation like this

```
choices = [
    "[2014-01-01] abcd",
    "[2014-01-01] cdef"
    "[2014-01-01] ghij"
]

def strip_date(s):
    return s[12:]

process.extract("abcde", choices, processor=strip_date, scorer=fuzz.ratio)
```

This example is contrived but not too unrealistic. 

In retrospect there probably shouldn't be a default `processor` at all, since the default scorer processes its own input. However, changing that would not be BC. 

The problem here, I think, is that there is a mismatch between the expected input to the custom scorer (in this case, ratio.partial_ratio) and the input to extract. Another reasonable solution is the following

```
In [28]: process.extract(
    utils.full_process("Santa Ana"), 
    ['Santa Ana', 'Manta'], 
   scorer=fuzz.partial_ratio)
Out[28]: [('Santa Ana', 100), ('Manta', 80)]
```
