### ISSUE TITLE
partial_ratio

### ISSUE THREAD

**Issue by matthieugomez** [seatgeek/fuzzywuzzy#99]
Great library. I have a quick question about the `partial_ratio` function.

```
fuzz.partial_ratio("mariners vs angels", "los angeles angels at seattle mariners")
```
ends up calling
```
SequenceMatcher(None, "mariners vs angels", "mariners").ratio()
```
Reading your blog post, I would have expected something like
```
SequenceMatcher(None, "mariners vs angels", "t seattle mariners").ratio()
```
So is the current behavior intended?

**Comment by rickhanlonii** [comment]
Hey @matthieugomez, thanks for the question. Yes that's intended and it turns out that both are called. 

Let me explain. First we get all the [matching substring blocks](https://github.com/seatgeek/fuzzywuzzy/blob/51f560f19e1f6dff76cad1df4a2549a542002544/fuzzywuzzy/fuzz.py#L74-L75):

```python
m = SequenceMatcher(None, shorter, longer)
blocks = m.get_matching_blocks()
```

This results in two tuples describing matching blocks:
```python
blocks = [
  Match(i=0, j=30, n=8),
  Match(i=18, j=38, n=0)  # the last triple is a dummy, `(len(a), len(b), 0)`, and is the only triple with `n==0`
]
```

For strings `a` and `b`, a `Match` as explained in a difflib comment [here](https://github.com/enthought/Python-2.7.3/blob/69fe0ffd2d85b4002cacae1f28ef2eb0f25e16ae/Lib/difflib.py#L463-L464) means that:
```python
a[i:i+n] == b[j:j+n]
```


Thus, for strings `mariners vs angels` and `los angeles angels at seattle mariners` we have one Match (and one dummy block for the full string, see [here](https://github.com/enthought/Python-2.7.3/blob/69fe0ffd2d85b4002cacae1f28ef2eb0f25e16ae/Lib/difflib.py#L471-L472)):
```python
"mariners vs angels"[0:0+8] == "los angeles angels at seattle mariners"[30:30+8] == "mariners"
```

We then run over each of the matching blocks and the dummy block representing the full string in [this way](https://github.com/seatgeek/fuzzywuzzy/blob/51f560f19e1f6dff76cad1df4a2549a542002544/fuzzywuzzy/fuzz.py#L83-L94):
```python
    scores = []
    for block in blocks:
        long_start = block[1] - block[0] if (block[1] - block[0]) > 0 else 0
        long_end = long_start + len(shorter)
        long_substr = longer[long_start:long_end]

        m2 = SequenceMatcher(None, shorter, long_substr)
        r = m2.ratio()
        if r > .995:
            return 100
        else:
            scores.append(r)
```
If you step through this block you'll see that we'll run both ratios:

```python
# This is a ratio on the matching block substring
SequenceMatcher(None, "mariners vs angels", "mariners").ratio()

# This is a ratio on the length - m substring
SequenceMatcher(None, "mariners vs angels", "t seattle mariners").ratio()
```

This gives us two scores `0.615` and `0.444`. We return the higher of the two--which is why it looks like we called `ratio` on just `mariners`. 

Let me know if you have any questions.

**Comment by josegonzalez** [comment]
Closing as I *think* @rickhanlonii handled your question.

**Comment by matthieugomez** [comment]
Thanks for the detailed explanation! I'm still not clear on why you want to compare "mariners vs angels" and "mariners" (rather than imposing that substrings of the longer string have length equal to the shorter string, by adding more characters if needed).
For instance, this introduce issues wrt symmetry
```julia
fuzz.partial_ratio("mariners vs angels", "t seattle mariners")
#> 61
fuzz.partial_ratio("t seattle mariners", "mariners vs angels")
#> 44
```
Do you do this because it yields better results?
